# ADVANCED OOP AND NUMPY

## INHERITANCE
- A class can inherit from other class
- Inheritance improves code reuse 
- Constructors, attributes, and , method are inherited from parent to child 
- The parent has no access to child class 
- child class can overrides method of parent class. It is called method overriding
- `super()` method is used to invoke parent class method and constructors

### Single inheritance 

In [6]:
class human:
    def __init__(self,name):
        self.name = name 
    def show(self):
        print(self.name + " is a person")
class Person(human):
    pass
class Professor(Person):
    pass


In [7]:
per = Professor("Guido Rossum")

In [8]:
per.name

'Guido Rossum'

In [9]:
per.show

<bound method human.show of <__main__.Professor object at 0x000001C3C2D59C70>>

In [10]:
p = Professor("James")

In [11]:
p.name

'James'

In [12]:
p.show()

James is a person


## Multiple inheritance

In [18]:
class Person:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name + "is a person")
class Teacher:
    def credit(self):
        print("He teaches python")
class PythonProgrammer(Person,Teacher):
    pass

In [21]:
p1=PythonProgrammer("Guido Rossum")

In [23]:
p1.credit()

He teaches python


In [24]:
p1.name

'Guido Rossum'

In [26]:
p1.show()

Guido Rossumis a person


### Hiearchical Inheritance

In [29]:
class Human:
    def __init__(self,name):
        self.name = name
    def show(self):
        print(self.name + "is a person")
class PythonProg(Human):
    pass
class JavaProg(Human):
    pass

In [30]:
p2=PythonProg("Guido Rossum")

In [31]:
p2.name

'Guido Rossum'

In [32]:
j = JavaProg("James Gosling")

## Constructor and method overriding

In [33]:
class Father:
    def __init__(self):
        self.money = 10000
        print("Father class constructor")
    def show(self):
        print("Father class method")
        
class Son(Father):
    def __init__(self):
        self.money = 100
        self.car = 'BMW'
        print("Son class constructor")
    def show(self):
        print("Son class method")


In [34]:
s = Son()

Son class constructor


In [35]:
s.car

'BMW'

In [36]:
s.money

100

In [37]:
s.show()

Son class method


In [38]:
f = Father()

Father class constructor


In [40]:
f.car #Parent class has no access of child class

AttributeError: 'Father' object has no attribute 'car'

In [41]:
f.show()

Father class method


## `super()` method
- If we write constructor in both the parent and child class, the parent class constructor is not available to child class 
- `super()` method is used to invoke parent class constructor and method from child class

In [44]:
class Father:
    def __init__(self):
        self.money = 10000
        print("Father class constructor")
    def show(self):
        print("Father class method")
        
class Son(Father):
    def __init__(self):
        self.money = 100
        self.car = 'BMW'
        super().__init__()
        print("Son class constructor")
    def show(self):
        super().show()
        print("Son class method")


In [45]:
s1 = Son()

Father class constructor
Son class constructor


In [46]:
s1.show()

Father class method
Son class method


In [47]:
s1.money

10000

In [48]:
s1.money = 900

In [50]:
s1.money

900

## WAP to create Book class with title, author and publisher as attributes. Book class has a display title and author.Create a derived class Cource with course as attribute. course class has a method named display which overrides the parent class and display title author and course 

In [69]:
class Book:
    def __init__(self,title,author,publisher):
        self.title=title
        self.author=author
        self.publisher=publisher
    def display(self):
        print(self.title ,"is a title of book")
        print(self.author, "is a author of book")
class Course(Book):
    def __init__(self,course):
        super().__init__("Javabook","James","Pearson")
        self.course=course
    def display(self):
        super().display()
        print(self.course, "is a course of book")
        print(self.publisher, "is a publisher of book")

    

In [70]:
c = Course("JAVA")

In [73]:
c.display()

Javabook is a title of book
James is a author of book
JAVA is a course of book
Pearson is a publisher of book


In [74]:
c.publisher

'Pearson'

In [77]:
c.display()

Javabook is a title of book
James is a author of book
JAVA is a course of book
Pearson is a publisher of book


## ABSTRACT CLASS 
- A class derived from ABC class which belongs to abc module is known as abstract class in python
```python
from abc import ABC,abstractmethod
```
>abc means abstract base class
- Abstract class can have concrete and abstract methods
- Abstract class needs to be extended and implemented in child class
- One cannot create objects of abstract class
- It is not necessary to have all methods abstract in abstract class 
- The abstract methods of abstarct class must be defined in child classes

In [91]:
from abc import ABC, abstractmethod

class Defence(ABC): # Abstract class
    def __init__(self): # Constructor
        self.id=101 # attribute
        
    @abstractmethod # abstract method
    def area(self):
        pass
    
    def gun(self): #concrete method
        print("The gun is AK47")

In [92]:
d = Defence() # NameError: name 'abstarctmethod' is not defined
# abstract class has no object possible 

TypeError: Can't instantiate abstract class Defence with abstract methods area

In [93]:
class Army(Defence):
    def area(self):
        print("The area is land ", self.id)

In [100]:
a.gun()

The gun is AK47


In [94]:
a = Army()

In [95]:
a.area()

The area is land  101


In [103]:
class Navy(Defence):
    def newarea(self):
        print("This will not work")

In [104]:
n = Navy()

TypeError: Can't instantiate abstract class Navy with abstract methods area

## WAP to create abstarct class Shape. It has abstract method calculate_area. Create derived classes Rectangle and circle and corresponding calculate area methods to find the area

In [105]:
from abc import ABC, abstractmethod
from math import pi
class Shape(ABC):
       
    @abstractmethod
    def calculate_area(self):
         pass

In [106]:
class Rectangle(Shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
    def calculate_area(self):
        return self.l * self.b

In [113]:
class Circle(Shape):
    def __init__(self,r):
        self.r=r
    def calculate_area(self):
        return pi*self.r*self.r

In [114]:
c = Circle(5)

In [115]:
c.calculate_area()

78.53981633974483

## Operators Overloading
```
__gt__ -> >
__lt__ -> <
__eq__ -> ==
__add__ -> +
__sub__ -> -
__mul__ -> *
__truediv__ -> /

## Demonstraction through fraction class 
```
Fraction1 = 5/8
Fraction2 = 2/3
```

In [14]:
class Fraction:
    def __init__(self,x,y):
        self.num = x
        self.den = y
    def __str__(self): # To print object we use str method 
        return f"{self.num}/{self.den}"
    def __add__(self,other):
        new_num = self.num * other.den + other.num*self.den
        new_den = self.den*other.den
        return f"{new_num}/{new_den}"
    def __sub__(self,other):
        new_num = self.num * other.den - other.num*self.den
        new_den = self.den*other.den
        return f"{new_num}/{new_den}"
    def __mul__(self,other):
        new_num = self.num * other.num 
        new_den = self.den*other.den
        return f"{new_num}/{new_den}"
    def __truediv__(self,other):
        new_num = self.num * other.den 
        new_den = self.den*other.num
        return f"{new_num}/{new_den}"
    def convert_decimal(self):
        return self.num / self.den
    def __eq__(self,other):
        return self.convert_decimal()==other.convert_decimal()
    def __lt__(self,other):
        return self.convert_decimal()<other.convert_decimal()
    def __gt__(self,other):
        return self.convert_decimal()>other.convert_decimal()

In [15]:
obj1 = Fraction(5,8)
obj2 = Fraction(2,3)

In [16]:
# str method
print(obj1)
print(obj2)

5/8
2/3


In [19]:
print(obj1 + obj2)
print(obj1 - obj2)
print(obj1 * obj2)
print(obj1 / obj2)
print(obj1.convert_decimal())
print(obj1==obj2)
print(obj1<obj2)
print(obj1>obj2)

31/24
-1/24
10/24
15/16
0.625
False
True
False


## WAP to create a class DATA with values as data member. Implement less than, greater than, and equality operator for two objects of the same class

In [26]:
class Data:
    def __init__(self,value):
        self.value = value
    def __eq__(self,other):
        return self.value == other.value
    def __lt__(self,other):
        return self.value < other.value
    def __gt__(self,other):
        return self.value > other.value

In [27]:
d1 = Data(30)
d2 = Data(40)

In [28]:
print(d1 == d2)
print(d1 < d2)
print(d1 > d2)

False
True
False


## METHOD RESOLUTION ORDER IN PYTHON
- It defines an order in which to search for the class to find out which method to use in case of multiple inheritance
- It is done through C3 linearlization algorithm
  

## Example Demonstration

In [29]:
class F:
    pass
class E:
    pass
class D:
    pass
class C(D,F):
    pass
class B(D,E):
    pass
class A(B,C):
    pass

In [30]:
A.mro()

[__main__.A,
 __main__.B,
 __main__.C,
 __main__.D,
 __main__.E,
 __main__.F,
 object]

# First Step

```
L[D] = DO
L[E] = EO
L[F] = FO

# Second Step 
```
MRO OF C = C + MERGE(L[D],L[F],DF)
= C + MERGE(DO,FO,DF)
= C + D + MERGE(O,FO,F)
= C + D + F + O
= CDFO
```

# Third Step
```
MRO OF B = B + MERGE(L[D],L[E],DE)
= B + MERGE(DO,EO,DE)
= B + D + MERGE(O,EO,E)
= B + D + E + O
= BDEO
```

# FORTH Step
```
MRO OF A = A + MERGE(L[B],L[C],BC)
= A + MERGE(BDEO,CDFO,BC)
= A + B + MERGE(DEO,CDFO,C)
= A + B + C + MERGE(DEO,DFO)
= A + B + C + D + MERGE(EO,FO)
= A + B + C + D + E + MERGE(O,FO)
= A + B + C + D + E + F + O
= ABCDEFO
```

In [36]:
#694
class A: #AO
    pass
class B: #BO
    pass
class C: #CO
    pass
class X(A,B): #XABO
    pass
class Y(C,A,B): #YCABO
    pass
class Z(A): #ZAO
    pass
class P(Z,Y,X): # P + MERGE(ZAO,YCABO,XABO,ZYX)   ==>  PZYCXABO
    pass

In [37]:
P.mro()

[__main__.P,
 __main__.Z,
 __main__.Y,
 __main__.C,
 __main__.X,
 __main__.A,
 __main__.B,
 object]

In [40]:
# 656
class A: pass #AO
class B: pass #BO
class C: pass #CO
class D:pass #DO
class E:pass #EO
class K1(C,A,B): pass #K1CABO
class K3(A,D): pass #K3ADO
class K2(B,D,E): pass #K2BDEO
class Z( K1,K3,K2): pass # Z + MERGE(K1CABO,K3ADO,K2BDEO,K1K3K2) ==> Z K1 C K3 A K2 B D E O

## Inconsistent Design 

In [39]:
class A: #AO
    pass
class B: #BO
    pass
class C(A,B): #CABO
    pass
class D(B,A): #DBAO
    pass
class X(C,D): # X + MERGE(CABO,DBAO,CD ==> XC    (NOT POSSIBLE MRO)
    pass



TypeError: Cannot create a consistent method resolution order (MRO) for bases A, B

# PB-634
```
Create a class called Student, having name and email as its data members and _init_(self, name, email) and putdata(self)
as bound methods. The _init_ function should assign the values passed as parameters to the requisite variables. The
putdata function should display the data of the student. Create another class called PhDguide having name, email, and
students as its data members. Here, the students variable is the list of students under the guide. The PhDguide class
should have four bound methods: _init_, putdata, add, and remove. The _init_ method should initialize the variables, the
putdata should show the data of the guide, include the list of students, the add method should add a student to the list of
students of the guide and the remove function should remove the student (if the student exists in the list of students of
that guide) from the list of students.

In [48]:
class Student:
    def __init__(self, name, email):
        self.name = name
        self.email = email
    def putdata(self):
        print(self.name)
        print(self.email)
class PhdGuide:
    def __init__(self, name, email):
        self.name = name
        self.email = email
        self.students = []
    def putdata(self):
        print("Guide name : ",self.name)
        print("Guide email : ",self.email)
        print("Students under the guide - ")
        for student in self.students:
            student.putdata()
            print("-------------------------")
    def addStudent(self,student):
        if student not in self.students:
            self.students.append(student)
            print("Student added to guide successfully")
    def removestudent(self,student):
        if student in self.students:
            self.students.remove(student)
            print("Student Removed Successfully")
        else:
            print("Student not found")

In [49]:
s1 = Student("Kasim","kasimhussain@gmail.com")
s2 = Student("James","James@gmail.com")


In [50]:
guide = PhdGuide("Dr Smith","Smith@gmail.com")

In [51]:
guide.addStudent(s1)

Student added to guide successfully


In [52]:
guide.putdata()

Guide name :  Dr Smith
Guide email :  Smith@gmail.com
Students under the guide - 
Kasim
kasimhussain@gmail.com
-------------------------


In [53]:
guide.removestudent(s1)

Student Removed Successfully


# NUMPY

### 1-D array

In [1]:
import numpy as np

In [2]:
np.array??

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [15]:
a = np.array([1,2,3],dtype = float) #1-D array

In [16]:
a

array([1., 2., 3.])

In [17]:
print(a)

[1. 2. 3.]


In [18]:
print(type(a))

<class 'numpy.ndarray'>


In [19]:
np.__version__

'2.1.3'

### 2-D Array

In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
print(b)

[[1 2 3]
 [4 5 6]]


### 3-D Array

In [24]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [25]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
print(a)

[1. 2. 3.]


### Attributes

In [27]:
print(a)
print(a.size)
print(a.ndim)
print(a.itemsize)
print(a.dtype)
print(a.shape)

[1. 2. 3.]
3
1
8
float64
(3,)


In [28]:
print(b)
print(b.size)
print(b.ndim)
print(b.itemsize)
print(b.dtype)
print(b.shape) # 2-row 3-column

[[1 2 3]
 [4 5 6]]
6
2
8
int64
(2, 3)


In [29]:
print(c)
print(c.size)
print(c.ndim)
print(c.itemsize)
print(c.dtype)
print(c.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
3
8
int64
(2, 2, 2)


### np.arange

In [30]:
d = np.arange(7)
print(d)

[0 1 2 3 4 5 6]


In [31]:
d = np.arange(3,7)
print(d)

[3 4 5 6]


In [32]:
d = np.arange(1,8,3)
print(d)

[1 4 7]


### Arithmetic Opeartion

In [35]:
a

array([1., 2., 3.])

In [36]:
print(a*3)
print(a**3)
print(a/3)
print(a//3)
print(a + 3)
print(a - 3)

[3. 6. 9.]
[ 1.  8. 27.]
[0.33333333 0.66666667 1.        ]
[0. 0. 1.]
[4. 5. 6.]
[-2. -1.  0.]


In [38]:
[1,2,3] + 3 # In list not possible 

TypeError: can only concatenate list (not "int") to list

### Reshape
- It changes the dimension of the given array
  

In [39]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4) #3-row and 4-col

In [40]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,3)


ValueError: cannot reshape array of size 12 into shape (3,3)

In [46]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(2,3,2) # 2-layer 3-row 2-col


In [47]:
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [48]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(6,1,2) 

In [49]:
print(a)

[[[ 1  2]]

 [[ 3  4]]

 [[ 5  6]]

 [[ 7  8]]

 [[ 9 10]]

 [[11 12]]]


In [50]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3,1)
print(a)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


### Numpy nditer 

In [51]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
for i in c:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [55]:
for i in np.nditer(c):
    print(i)

1
2
3
4
5
6
7
8


### ndenumerate 

In [56]:
for i,v in np.ndenumerate(c):
    print("Index-",i,"Value-",v)

Index- (0, 0, 0) Value- 1
Index- (0, 0, 1) Value- 2
Index- (0, 1, 0) Value- 3
Index- (0, 1, 1) Value- 4
Index- (1, 0, 0) Value- 5
Index- (1, 0, 1) Value- 6
Index- (1, 1, 0) Value- 7
Index- (1, 1, 1) Value- 8


### `np.concatenate`
- It is used to join two arrays along the axis 

In [58]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [59]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [60]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [61]:
np.concatenate((c,d),axis=2) # throws error: inconsistent dimensions

AxisError: axis 2 is out of bounds for array of dimension 2

### Array Split 
- It is opposite to join function
- It splits the given array based on the split criteria
- For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

In [62]:
a = np.arange(8)
a


array([0, 1, 2, 3, 4, 5, 6, 7])

In [63]:
np.array_split??

Signature:       np.array_split(ary, indices_or_sections, axis=0)
Call signature:  np.array_split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function array_split at 0x000001B9AE5EFB00>
File:            c:\programdata\anaconda3\lib\site-packages\numpy\lib\_shape_base_impl.py
Source:         
@array_function_dispatch(_array_split_dispatcher)
def array_split(ary, indices_or_sections, axis=0):
    """
    Split an array into multiple sub-arrays.

    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.

    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> import numpy as np
    >>> x = np

In [65]:
np.array_split(2)

TypeError: array_split() missing 1 required positional argument: 'indices_or_sections'

In [66]:
np.array_split(a,2)


[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

In [67]:
np.array_split(a,5)


[array([0, 1]), array([2, 3]), array([4, 5]), array([6]), array([7])]

In [68]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

## `np.where`
- It returns the indices of elements of an input array where the given condition is satisfied

In [69]:
a = np.array([45,55,23,34,87,57,89,86,93])

In [70]:
np.where(a>50) # returns indices where condition satisfy

(array([1, 4, 5, 6, 7, 8]),)

In [71]:
np.where(a>50,0,a)

array([45,  0, 23, 34,  0,  0,  0,  0,  0])

In [72]:
np.where(a%2 ==0 ,0,a)

array([45, 55, 23,  0, 87, 57, 89,  0, 93])

## WAP to return array of items by taking the third column from all the rows 
```
samplearray =
np.array([[11,22,33],[44,55,66],[77,88,99]])
```

In [73]:
a = np.array([[11,22,33],[44,55,66],[77,88,99]])

In [74]:
print(a)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [80]:
print(a[:,2])

[33 66 99]


In [83]:
print(a[:1,1])

[22]


## WAP
```

for a given numpy array of farenheit values = [0,12,45.21,34.99,99.91,32] converts value to celsius values.
After converting the values, sort the array and find the position of 0
```

In [84]:
import numpy as np
fah = np.array([0,12,45.21,34.99,99.91,32])
cel = (fah-32) * 5/9
print(cel)

[-17.77777778 -11.11111111   7.33888889   1.66111111  37.72777778
   0.        ]


### Sort the array


In [85]:
a = np.sort(cel)
print(a)

[-17.77777778 -11.11111111   0.           1.66111111   7.33888889
  37.72777778]


In [86]:
indexofzero = np.where(a==0)
print(indexofzero)

(array([2]),)


### Swap the Columns 

In [89]:
a = np.array([
    [0,1,2,3],
    [4,5,6,7],
    [8,9,10,11]
])

In [90]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b = np.array([
    
])

### Sorting 

In [91]:
import numpy as np
arr = np.array([[3,2,4],[5,0,1]])
print(arr)

[[3 2 4]
 [5 0 1]]


In [92]:
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [94]:
print(np.sort(arr,axis=0))

[[3 0 1]
 [5 2 4]]
